"""
Shared ORM base and mixins used by every module's models.py.

Every table in the system gets a UUID primary key and created_at/updated_at
timestamps via these mixins, so that's never hand-rolled per-module.
"""
import uuid
from datetime import datetime

from sqlalchemy import DateTime, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class UUIDPKMixin:
    """
    UUID primary key. Generated by Postgres server-side (gen_random_uuid()) in
    production, and by Python (default=uuid4) as a portable fallback — the latter
    is what makes the model layer testable on SQLite, which has no such function.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
    )


class TimestampMixin:
    """Adds created_at / updated_at, both maintained by the database."""

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class SoftDeleteMixin:
    """
    Adds deleted_at for tables that must never lose historical rows
    (customers, products, categories — anything referenced by past orders).
    Repositories filter `deleted_at IS NULL` by default; see BaseRepository.
    """

    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True, default=None)

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None
