"""initial schema

Creates the complete v1 schema from the SQLAlchemy metadata. Subsequent
schema changes should be autogenerated as incremental migrations against a
live Postgres (`alembic revision --autogenerate -m "..."`).

Requires the pgcrypto extension for gen_random_uuid().

Revision ID: 0001_initial
Revises:
Create Date: 2026-01-01
"""
from alembic import op

from app.shared.models.registry import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # gen_random_uuid() lives in pgcrypto on older Postgres; harmless if already present.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
